package dbschema

import (
	"fmt"
	"strings"
)

// RenderSchemaSQL builds a readable CREATE TABLE backup snapshot of the
// discovered tables. It is not guaranteed to be byte-for-byte re-runnable
// against every engine dialect — it exists as a reference/backup artifact,
// not a migration script; EF Core migrations remain the primary path.
func RenderSchemaSQL(tables []Table) string {
	var b strings.Builder
	b.WriteString("-- Generated by aspgen import-db. Reference snapshot only; not a migration script.\n\n")
	for _, t := range tables {
		fmt.Fprintf(&b, "CREATE TABLE %s (\n", t.Name)
		for i, c := range t.Columns {
			null := "NOT NULL"
			if c.Nullable {
				null = "NULL"
			}
			suffix := ""
			if i < len(t.Columns)-1 {
				suffix = ","
			}
			pk := ""
			if c.IsPrimaryKey {
				pk = " PRIMARY KEY"
			}
			fmt.Fprintf(&b, "    %s %s %s%s%s\n", c.Name, c.RawType, null, pk, suffix)
		}
		b.WriteString(");\n\n")
	}
	return b.String()
}
