package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// addEntityFieldCmd adds one or more new scalar properties to an
// already-generated entity/aggregate, patching every already-rendered layer
// (Domain/aggregate class, persistence, API DTOs/handlers, seed data, WPF
// and Renoir/Blazor UI) in place instead of re-rendering whole files.
func addEntityFieldCmd(r addRequest, m *Manifest, d *data) error {
	if !validIdentifier(r.Name) {
		return fmt.Errorf("invalid entity name %q", r.Name)
	}
	existing := findEntityMeta(m.Entities, r.Name)
	if existing == nil {
		return fmt.Errorf("entity %q not found; add it first with 'aspgen add entity' or 'aspgen add aggregate'", r.Name)
	}
	newProps, err := parseProperties(r.Args)
	if err != nil {
		return err
	}
	existingNames := map[string]bool{}
	for _, p := range existing.Properties {
		existingNames[p.Name] = true
	}
	for _, p := range newProps {
		if existingNames[p.Name] {
			return fmt.Errorf("entity %q already has a property %q", r.Name, p.Name)
		}
	}

	if existing.Context != "" {
		if err := patchRenoirAggregateField(r, m, *existing, newProps); err != nil {
			return err
		}
	} else {
		if err := patchEntityField(r, m, *existing, newProps); err != nil {
			return err
		}
	}

	updated := append(append([]Property{}, existing.Properties...), newProps...)
	m.Entities = appendEntityMeta(m.Entities, EntityMeta{Name: existing.Name, Context: existing.Context, Properties: updated})
	return nil
}

func findEntityMeta(entities []EntityMeta, name string) *EntityMeta {
	for i := range entities {
		if entities[i].Name == name {
			return &entities[i]
		}
	}
	return nil
}

// ---- low-level text-patch primitives -------------------------------------

// patchErr reports that description's expected pattern anchor was not found,
// meaning the file was likely hand-edited or generated by a different
// template revision than this patch logic expects.
func patchErr(description, anchor string) error {
	return fmt.Errorf("%s: expected pattern not found (file may have been modified): %.80q", description, anchor)
}

// insertBeforeMarker inserts insertion immediately before marker, once.
func insertBeforeMarker(content, marker, insertion string) (string, bool) {
	if !strings.Contains(content, marker) {
		return content, false
	}
	return strings.Replace(content, marker, insertion+"\n"+marker, 1), true
}

// insertAfterAnchor inserts insertion immediately after every (count) or the
// first (count=1) occurrence of anchor.
func insertAfterAnchor(content, anchor, insertion string, count int) (string, bool) {
	if !strings.Contains(content, anchor) {
		return content, false
	}
	return strings.Replace(content, anchor, anchor+insertion, count), true
}

// insertLinesInBlock finds signatureAnchor, then the block opened by the
// next "{\n" and closed by the next "\n    }" after it, and appends any of
// lines not already present just before the closing brace. Used for method
// bodies (validators, Configure(), Editor classes) that may have no
// existing per-property line to anchor on.
func insertLinesInBlock(content, signatureAnchor string, lines []string) (string, bool) {
	sigIdx := strings.Index(content, signatureAnchor)
	if sigIdx < 0 {
		return content, false
	}
	openRel := strings.Index(content[sigIdx:], "{\n")
	if openRel < 0 {
		return content, false
	}
	bodyStart := sigIdx + openRel + len("{\n")
	closeRel := strings.Index(content[bodyStart:], "\n    }")
	if closeRel < 0 {
		return content, false
	}
	span := content[bodyStart : bodyStart+closeRel]
	var toAdd []string
	for _, line := range lines {
		if !strings.Contains(span, line) {
			toAdd = append(toAdd, line)
		}
	}
	if len(toAdd) == 0 {
		return content, false
	}
	insertion := "\n" + strings.Join(toAdd, "\n")
	return content[:bodyStart+closeRel] + insertion + content[bodyStart+closeRel:], true
}

// replaceArgList replaces every verbatim occurrence of the argument/param
// list rendered from oldProps with the list rendered from oldProps+addProps.
// It is a no-op if the old rendering can't be found (already patched, or an
// unexpected file shape).
//
// Every argument/param list this is used for is rendered immediately after
// an opening "(" (constructor/method params, record params, or a call's
// argument list) — sometimes on the same line, sometimes with a newline and
// indentation in between for multi-line record declarations. The match is
// anchored on that leading "(" (allowing only whitespace in between) so a
// short rendering (e.g. leadingSpaceJoin's " request.Name, request.Age")
// can't be found as a false-positive substring inside a longer, unrelated
// rendering that happens to share a trailing portion (e.g. tokenJoin("id")'s
// "id, request.Name, request.Age") — the whitespace-only gap after "("
// can't stretch over the non-whitespace "id, " prefix.
func replaceArgList(content string, oldProps, addProps []Property, render func(Property) string, format func([]string) string) (string, bool) {
	oldPieces := renderPieces(oldProps, render)
	newPieces := renderPieces(append(append([]Property{}, oldProps...), addProps...), render)
	oldCore := format(oldPieces)
	newCore := format(newPieces)
	if oldCore == newCore || oldCore == "" {
		return content, false
	}
	pattern := regexp.MustCompile(`\(([ \t\r\n]*)` + regexp.QuoteMeta(oldCore))
	matches := pattern.FindAllStringSubmatchIndex(content, -1)
	if matches == nil {
		return content, false
	}
	var b strings.Builder
	last := 0
	for _, m := range matches {
		b.WriteString(content[last:m[0]])
		b.WriteString("(")
		b.WriteString(content[m[2]:m[3]])
		b.WriteString(newCore)
		last = m[1]
	}
	b.WriteString(content[last:])
	return b.String(), true
}

func renderPieces(props []Property, render func(Property) string) []string {
	pieces := make([]string, len(props))
	for i, p := range props {
		pieces[i] = render(p)
	}
	return pieces
}

func leadingSpaceJoin(pieces []string) string {
	if len(pieces) == 0 {
		return ""
	}
	return " " + strings.Join(pieces, ", ")
}

func plainCommaJoin(pieces []string) string {
	return strings.Join(pieces, ", ")
}

func tokenJoin(token string) func([]string) string {
	return func(pieces []string) string {
		if len(pieces) == 0 {
			return token
		}
		return token + ", " + strings.Join(pieces, ", ")
	}
}

func recordParamPiece(p Property) string { return p.CSharpType + " " + p.Name }
func ctorParamPiece(p Property) string   { return p.CSharpType + " " + camel(p.Name) }
func prefixedPiece(prefix string) func(Property) string {
	return func(p Property) string { return prefix + "." + p.Name }
}

// fileExists reports whether path exists and is a regular file.
func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

// readPatchFile reads path and normalizes CRLF line endings to LF so every
// patch primitive can rely on plain "\n" anchors regardless of how the file
// happens to be saved on disk.
func readPatchFile(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	return strings.ReplaceAll(string(b), "\r\n", "\n"), nil
}

// writePatchFile writes content back to path, restoring CRLF line endings if
// the file on disk currently uses them (readPatchFile normalizes to LF, so
// this undoes that for files that were originally CRLF).
func writePatchFile(path, content string, dryRun bool) error {
	if b, err := os.ReadFile(path); err == nil && strings.Contains(string(b), "\r\n") {
		content = strings.ReplaceAll(content, "\n", "\r\n")
	}
	return writeMarkerFile(path, content, dryRun)
}

// ---- rendering helpers for per-type property lines -----------------------

func domainAssignLine(p Property, guard bool) string {
	rhs := camel(p.Name)
	if guard {
		switch strings.TrimSuffix(p.CSharpType, "?") {
		case "string", "Guid", "DateOnly", "DateTime":
			rhs = fmt.Sprintf("DomainGuard.Required(%s, nameof(%s))", camel(p.Name), camel(p.Name))
		}
	}
	return "        " + p.Name + " = " + rhs + ";"
}

func autoPropLine(p Property, access string) string {
	return "    public " + p.CSharpType + " " + p.Name + " { get; " + access + "; } = default!;"
}

func validatorRuleLine(p Property, renoir bool) string {
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "string":
		return "        RuleFor(x => x." + p.Name + ").NotEmpty().WithMessage(\"" + p.Name + " is required.\");"
	case "Guid":
		if renoir {
			return "        RuleFor(x => x." + p.Name + ").NotEmpty().WithMessage(\"" + p.Name + " must not be empty.\");"
		}
		return "        RuleFor(x => x." + p.Name + ").NotEmpty();"
	case "DateOnly":
		if renoir {
			return "        RuleFor(x => x." + p.Name + ").Must(value => value != default).WithMessage(\"" + p.Name + " must be a valid date.\");"
		}
	case "DateTime":
		if renoir {
			return "        RuleFor(x => x." + p.Name + ").Must(value => value != default).WithMessage(\"" + p.Name + " must be a valid date and time.\");"
		}
	}
	return ""
}

// argPatch is one (render, format) combination replaceArgList tries against
// a file's content; used when a file has several distinct argument lists
// built from the same property set (e.g. a handler's ctor call and its
// response-mapping call).
type argPatch struct {
	render func(Property) string
	format func([]string) string
}

// patchArgListsInFile applies every patch in patches (each independently, on
// the same evolving content) and writes the file back if at least one patch
// matched. It errors only if none of the patches found anything to replace.
func patchArgListsInFile(path string, oldProps, newProps []Property, patches []argPatch, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	original := content
	for _, p := range patches {
		if newContent, changed := replaceArgList(content, oldProps, newProps, p.render, p.format); changed {
			content = newContent
		}
	}
	if content == original {
		return fmt.Errorf("patch %s: no matching argument list found", path)
	}
	return writePatchFile(path, content, dryRun)
}

// ---- plain entity / simple / DDD webapi layers ----------------------------

func patchEntityField(r addRequest, m *Manifest, existing EntityMeta, newProps []Property) error {
	project := r.Project
	namespace := m.Project
	backend := r.Backend

	if isNonSimpleWebAPI(*m) || isLocalDDDWpf(*m, backend) {
		path := filepath.Join(project, "src", "Domain", "Entities", existing.Name+".cs")
		if err := patchDomainEntity(path, existing, newProps, r.DryRun); err != nil {
			return err
		}
	}

	if backend == "simple" {
		modelPath := filepath.Join(project, "src", "WebApi", "Models", existing.Name+".cs")
		if err := patchSimpleModel(modelPath, newProps, r.DryRun); err != nil {
			return err
		}
		endpointsPath := filepath.Join(project, "src", "WebApi", "Features", existing.Name, existing.Name+"Endpoints.cs")
		if err := patchSimpleEndpoints(endpointsPath, existing, newProps, r.DryRun); err != nil {
			return err
		}
	} else if backend == "ddd" && isWebAPI(*m) {
		if err := patchDDDWebApiFeature(project, namespace, existing, newProps, r.DryRun); err != nil {
			return err
		}
	}

	if isWPFProject(*m) {
		wpfBackend := backend
		if backend == "ddd" && !isWebAPI(*m) {
			wpfBackend = "ddd-local"
		}
		if err := patchWpfEntity(project, existing, newProps, wpfBackend, componentTheme(m.Components), r.DryRun); err != nil {
			return err
		}
	}

	if componentSeed(m.Components) == "dummy" && backend != "" {
		seedBackend := backend
		if backend == "ddd" && !isWebAPI(*m) {
			seedBackend = "ddd-local"
		}
		if err := patchSeedField(project, seedBackend, existing.Name, existing.Properties, newProps, componentSeedCount(m.Components), r.DryRun); err != nil {
			return err
		}
	}

	return nil
}

func patchDomainEntity(path string, existing EntityMeta, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	description := "domain entity " + path

	newContent, changed := replaceArgList(content, existing.Properties, newProps, ctorParamPiece, leadingSpaceJoin)
	if !changed {
		return fmt.Errorf("%s: constructor/Update parameter list not found", description)
	}
	content = newContent

	last := existing.Properties[len(existing.Properties)-1]
	anchor := domainAssignLine(last, false)
	var lines []string
	for _, p := range newProps {
		lines = append(lines, domainAssignLine(p, false))
	}
	newContent, changed = insertAfterAnchor(content, anchor, "\n"+strings.Join(lines, "\n"), -1)
	if !changed {
		return fmt.Errorf("%s: constructor/Update assignment %q not found", description, anchor)
	}
	content = newContent

	var declLines []string
	for _, p := range newProps {
		declLines = append(declLines, autoPropLine(p, "private set"))
	}
	newContent, changed = insertBeforeMarker(content, "    // aspgen:navigation", strings.Join(declLines, "\n"))
	if !changed {
		return missingMarkerErr(path, "// aspgen:navigation")
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchSimpleModel(path string, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	var lines []string
	for _, p := range newProps {
		lines = append(lines, autoPropLine(p, "set"))
	}
	newContent, changed := insertBeforeMarker(content, "    // aspgen:navigation", strings.Join(lines, "\n"))
	if !changed {
		return missingMarkerErr(path, "// aspgen:navigation")
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchSimpleEndpoints(path string, existing EntityMeta, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	last := existing.Properties[len(existing.Properties)-1]
	anchor := "            entity." + last.Name + " = request." + last.Name + ";"
	var lines []string
	for _, p := range newProps {
		lines = append(lines, "            entity."+p.Name+" = request."+p.Name+";")
	}
	newContent, changed := insertAfterAnchor(content, anchor, "\n"+strings.Join(lines, "\n"), 1)
	if !changed {
		return fmt.Errorf("simple endpoints %s: assignment %q not found", path, anchor)
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchValidatorFile(path, ctorSignature string, newProps []Property, renoir bool, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	var lines []string
	for _, p := range newProps {
		if line := validatorRuleLine(p, renoir); line != "" {
			lines = append(lines, line)
		}
	}
	if len(lines) == 0 {
		return nil
	}
	newContent, changed := insertLinesInBlock(content, ctorSignature, lines)
	if !changed {
		return fmt.Errorf("validator %s: constructor %q not found or rule already present", path, ctorSignature)
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchDDDWebApiFeature(project, namespace string, existing EntityMeta, newProps []Property, dryRun bool) error {
	dir := filepath.Join(project, "src", "Application", "Features", existing.Name)
	name := existing.Name
	old := existing.Properties

	if err := patchArgListsInFile(filepath.Join(dir, name+"Request.cs"), old, newProps,
		[]argPatch{{recordParamPiece, leadingSpaceJoin}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, name+"Response.cs"), old, newProps,
		[]argPatch{{recordParamPiece, tokenJoin("long Id")}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Create"+name+"Command.cs"), old, newProps,
		[]argPatch{{recordParamPiece, leadingSpaceJoin}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Update"+name+"Command.cs"), old, newProps,
		[]argPatch{{recordParamPiece, tokenJoin("long Id")}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Create"+name+"Handler.cs"), old, newProps,
		[]argPatch{
			{prefixedPiece("request"), leadingSpaceJoin},
			{prefixedPiece("entity"), tokenJoin("entity.Id")},
		}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Update"+name+"Handler.cs"), old, newProps,
		[]argPatch{{prefixedPiece("request"), leadingSpaceJoin}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Get"+name+"ByIdHandler.cs"), old, newProps,
		[]argPatch{{prefixedPiece("entity"), tokenJoin("entity.Id")}}, dryRun); err != nil {
		return err
	}
	if err := patchArgListsInFile(filepath.Join(dir, "Get"+name+"sHandler.cs"), old, newProps,
		[]argPatch{{prefixedPiece("entity"), tokenJoin("entity.Id")}}, dryRun); err != nil {
		return err
	}
	if searchHandlerPath := filepath.Join(dir, "Search"+name+"sHandler.cs"); fileExists(searchHandlerPath) {
		if err := patchArgListsInFile(searchHandlerPath, old, newProps,
			[]argPatch{{prefixedPiece("entity"), tokenJoin("entity.Id")}}, dryRun); err != nil {
			return err
		}
	}
	if err := patchValidatorFile(filepath.Join(dir, "Create"+name+"Validator.cs"), "public Create"+name+"Validator()", newProps, false, dryRun); err != nil {
		return err
	}
	if err := patchValidatorFile(filepath.Join(dir, "Update"+name+"Validator.cs"), "public Update"+name+"Validator()", newProps, false, dryRun); err != nil {
		return err
	}
	webApiDir := filepath.Join(project, "src", "WebApi", "Features", name)
	if err := patchArgListsInFile(filepath.Join(webApiDir, name+"Endpoints.cs"), old, newProps,
		[]argPatch{
			{prefixedPiece("request"), leadingSpaceJoin},
			{prefixedPiece("request"), tokenJoin("id")},
		}, dryRun); err != nil {
		return err
	}
	return nil
}

// ---- seed data --------------------------------------------------------

func patchSeedField(project, seedBackend, entity string, oldProps, newProps []Property, count int, dryRun bool) error {
	path := filepath.Join(project, "src", "WebApi", "Data", "DatabaseSeeder.cs")
	if seedBackend == "ddd" {
		path = filepath.Join(project, "src", "WebApi", "Seeding", "DatabaseSeeder.cs")
	} else if seedBackend == "ddd-local" {
		path = filepath.Join(project, "src", "Infrastructure", "Seeding", "DatabaseSeeder.cs")
	}
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	oldBlock := renderSeedBlock(seedBackend, entity, oldProps, count)
	if !strings.Contains(content, oldBlock) {
		return nil
	}
	allProps := append(append([]Property{}, oldProps...), newProps...)
	newBlock := renderSeedBlock(seedBackend, entity, allProps, count)
	newContent := strings.Replace(content, oldBlock, newBlock, 1)
	return writePatchFile(path, newContent, dryRun)
}

// ---- WPF layer ----------------------------------------------------------

func wpfDataGridColumnXml(p Property) string {
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "bool":
		return `<DataGridCheckBoxColumn Header="` + p.DisplayName + `" Binding="{Binding ` + p.Name + `}" />`
	case "DateOnly":
		return `<DataGridTextColumn Header="` + p.DisplayName + `" Binding="{Binding ` + p.Name + `, StringFormat=d}" />`
	case "DateTime":
		return `<DataGridTextColumn Header="` + p.DisplayName + `" Binding="{Binding ` + p.Name + `, StringFormat=g}" />`
	default:
		return `<DataGridTextColumn Header="` + p.DisplayName + `" Binding="{Binding ` + p.Name + `}" />`
	}
}

func wpfEditControlBlock(p Property, theme string) string {
	var b strings.Builder
	b.WriteString("                <StackPanel Margin=\"0,8,0,0\">\n")
	if theme == "wpfui" {
		b.WriteString("                    <ui:TextBlock Foreground=\"{DynamicResource TextFillColorSecondaryBrush}\" Text=\"" + p.DisplayName + "\" />\n")
	} else {
		b.WriteString("                    <TextBlock Text=\"" + p.DisplayName + "\" />\n")
	}
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "DateOnly":
		if theme == "wpfui" {
			b.WriteString("                    <ui:CalendarDatePicker Margin=\"0,4,0,0\" Date=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
		} else {
			b.WriteString("                    <DatePicker Margin=\"0,4,0,0\" SelectedDate=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
		}
	case "DateTime":
		if theme == "wpfui" {
			b.WriteString("                    <StackPanel Orientation=\"Horizontal\">\n")
			b.WriteString("                        <ui:CalendarDatePicker Width=\"180\" Margin=\"0,4,8,0\" Date=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
			b.WriteString("                        <ui:TimePicker Width=\"140\" Margin=\"0,4,0,0\" SelectedTime=\"{Binding Form." + p.Name + "Time, Mode=TwoWay}\" />\n")
			b.WriteString("                    </StackPanel>\n")
		} else {
			b.WriteString("                    <DatePicker Margin=\"0,4,0,0\" SelectedDate=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
		}
	case "bool":
		if theme == "wpfui" {
			b.WriteString("                    <ui:ToggleSwitch Margin=\"0,4,0,0\" IsChecked=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
		} else {
			b.WriteString("                    <CheckBox Margin=\"0,4,0,0\" IsChecked=\"{Binding Form." + p.Name + ", Mode=TwoWay}\" />\n")
		}
	case "int", "long", "decimal", "float":
		if theme == "wpfui" {
			b.WriteString("                    <ui:NumberBox Margin=\"0,4,0,0\" ClearButtonEnabled=\"True\" PlaceholderText=\"" + p.DisplayName + "\" Text=\"{Binding Form." + p.Name + ", UpdateSourceTrigger=PropertyChanged}\" />\n")
		} else {
			b.WriteString("                    <TextBox Margin=\"0,4,0,0\" Text=\"{Binding Form." + p.Name + ", UpdateSourceTrigger=PropertyChanged}\" />\n")
		}
	default:
		if theme == "wpfui" {
			b.WriteString("                    <ui:TextBox Margin=\"0,4,0,0\" ClearButtonEnabled=\"True\" PlaceholderText=\"" + p.DisplayName + "\" Text=\"{Binding Form." + p.Name + ", UpdateSourceTrigger=PropertyChanged}\" />\n")
		} else {
			b.WriteString("                    <TextBox Margin=\"0,4,0,0\" Text=\"{Binding Form." + p.Name + ", UpdateSourceTrigger=PropertyChanged}\" />\n")
		}
	}
	b.WriteString("                </StackPanel>")
	return b.String()
}

func patchWpfView(path string, oldProps, newProps []Property, theme string, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	last := oldProps[len(oldProps)-1]

	colAnchor := "                " + wpfDataGridColumnXml(last) + "\n"
	var colLines []string
	for _, p := range newProps {
		colLines = append(colLines, "                "+wpfDataGridColumnXml(p))
	}
	newContent, changed := insertAfterAnchor(content, colAnchor, strings.Join(colLines, "\n")+"\n", 1)
	if !changed {
		return fmt.Errorf("wpf view %s: DataGrid column for %q not found", path, last.Name)
	}
	content = newContent

	editAnchor := wpfEditControlBlock(last, theme)
	var editBlocks []string
	for _, p := range newProps {
		editBlocks = append(editBlocks, wpfEditControlBlock(p, theme))
	}
	newContent, changed = insertAfterAnchor(content, editAnchor, "\n"+strings.Join(editBlocks, "\n"), 1)
	if !changed {
		return fmt.Errorf("wpf view %s: edit form block for %q not found", path, last.Name)
	}
	return writePatchFile(path, newContent, dryRun)
}

func tryBuildLines(p Property) []string {
	c := camel(p.Name)
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "bool":
		return []string{"        var " + c + " = Form." + p.Name + ";"}
	case "DateOnly":
		return []string{
			"        if (Form." + p.Name + " is null) return Invalid(nameof(Form." + p.Name + "));",
			"        var " + c + " = DateOnly.FromDateTime(Form." + p.Name + ".Value);",
		}
	case "DateTime":
		return []string{
			"        if (Form." + p.Name + " is null) return Invalid(nameof(Form." + p.Name + "));",
			"        if (Form." + p.Name + "Time is null) return Invalid(nameof(Form." + p.Name + "));",
			"        var " + c + " = DateTime.SpecifyKind(Form." + p.Name + ".Value.Date + Form." + p.Name + "Time.Value, DateTimeKind.Unspecified);",
		}
	case "string":
		return []string{
			"        var " + c + " = Form." + p.Name + ".Trim();",
			"        if (" + c + ".Length == 0) return Invalid(nameof(Form." + p.Name + "));",
		}
	case "int", "long", "decimal", "float", "Guid":
		return []string{"        if (!" + p.CSharpType + ".TryParse(Form." + p.Name + ", out var " + c + ")) return Invalid(nameof(Form." + p.Name + "));"}
	default:
		return []string{"        var " + c + " = Form." + p.Name + ";"}
	}
}

func wpfEditorPropertyBlock(p Property) string {
	c := camel(p.Name)
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "bool":
		return "    private bool " + c + ";\n    public bool " + p.Name + " { get => " + c + "; set => SetProperty(ref " + c + ", value); }"
	case "DateOnly", "DateTime":
		block := "    private DateTime? " + c + ";\n    public DateTime? " + p.Name + " { get => " + c + "; set => SetProperty(ref " + c + ", value); }"
		if strings.TrimSuffix(p.CSharpType, "?") == "DateTime" {
			block += "\n    private TimeSpan? " + c + "Time;\n    public TimeSpan? " + p.Name + "Time { get => " + c + "Time; set => SetProperty(ref " + c + "Time, value); }"
		}
		return block
	default:
		return "    private string " + c + " = string.Empty;\n    public string " + p.Name + " { get => " + c + "; set => SetProperty(ref " + c + ", value); }"
	}
}

func wpfResetLine(p Property) string {
	switch strings.TrimSuffix(p.CSharpType, "?") {
	case "bool":
		return "        " + p.Name + " = item?." + p.Name + " ?? false;"
	case "DateOnly":
		return "        " + p.Name + " = item is null ? null : item." + p.Name + ".ToDateTime(TimeOnly.MinValue);"
	case "DateTime":
		return "        " + p.Name + " = item?." + p.Name + ";\n        " + p.Name + "Time = item?." + p.Name + ".TimeOfDay;"
	default:
		return "        " + p.Name + " = item is null ? string.Empty : item." + p.Name + ".ToString();"
	}
}

func patchWpfViewModel(path, entityName string, oldProps, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}

	var tryBuildAll []string
	for _, p := range newProps {
		tryBuildAll = append(tryBuildAll, tryBuildLines(p)...)
	}
	// Insert right before the final "value = new {Entity}Row(...)" line
	// rather than at the end of the method body: TryBuild builds every local
	// variable first and only constructs/returns at the very end, so new
	// per-property locals must be declared before that point (inserting
	// after "return true;" would produce unreachable, use-before-declare
	// code).
	marker := "        value = new " + entityName + "Row("
	newContent, changed := insertBeforeMarker(content, marker, strings.Join(tryBuildAll, "\n"))
	if !changed {
		return fmt.Errorf("wpf viewmodel %s: TryBuild %q line not found", path, marker)
	}
	content = newContent

	newContent, changed = replaceArgList(content, oldProps, newProps, func(p Property) string { return camel(p.Name) }, tokenJoin("editingId"))
	if !changed {
		return fmt.Errorf("wpf viewmodel %s: Row constructor call not found", path)
	}
	content = newContent

	last := oldProps[len(oldProps)-1]
	editorAnchor := wpfEditorPropertyBlock(last)
	var editorBlocks []string
	for _, p := range newProps {
		editorBlocks = append(editorBlocks, wpfEditorPropertyBlock(p))
	}
	newContent, changed = insertAfterAnchor(content, editorAnchor, "\n"+strings.Join(editorBlocks, "\n"), 1)
	if !changed {
		return fmt.Errorf("wpf viewmodel %s: Editor property block for %q not found", path, last.Name)
	}
	content = newContent

	resetAnchor := wpfResetLine(last)
	var resetLines []string
	for _, p := range newProps {
		resetLines = append(resetLines, wpfResetLine(p))
	}
	newContent, changed = insertAfterAnchor(content, resetAnchor, "\n"+strings.Join(resetLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("wpf viewmodel %s: Reset line for %q not found", path, last.Name)
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchWpfStoreDddLocal(path string, existing EntityMeta, newProps []Property, dryRun bool) error {
	patches := []argPatch{
		{prefixedPiece("x"), tokenJoin("x.Id")},
		{prefixedPiece("value"), plainCommaJoin},
		{prefixedPiece("created"), tokenJoin("created.Id")},
		{prefixedPiece("existing"), tokenJoin("existing.Id")},
	}
	return patchArgListsInFile(path, existing.Properties, newProps, patches, dryRun)
}

func patchWpfEntity(project string, existing EntityMeta, newProps []Property, backend, theme string, dryRun bool) error {
	dir := filepath.Join(project, "src", "Desktop", "Modules", existing.Name)

	rowPath := filepath.Join(dir, "Models", existing.Name+"Row.cs")
	if err := patchArgListsInFile(rowPath, existing.Properties, newProps,
		[]argPatch{{recordParamPiece, tokenJoin("long Id")}}, dryRun); err != nil {
		return err
	}

	viewPath := filepath.Join(dir, "Views", existing.Name+"View.xaml")
	if err := patchWpfView(viewPath, existing.Properties, newProps, theme, dryRun); err != nil {
		return err
	}

	vmPath := filepath.Join(dir, "ViewModels", existing.Name+"ViewModel.cs")
	if err := patchWpfViewModel(vmPath, existing.Name, existing.Properties, newProps, dryRun); err != nil {
		return err
	}

	if backend == "ddd-local" {
		storePath := filepath.Join(dir, "Services", existing.Name+"Store.cs")
		if err := patchWpfStoreDddLocal(storePath, existing, newProps, dryRun); err != nil {
			return err
		}
	}
	return nil
}

// ---- Renoir/Blazor aggregate layer ---------------------------------------

func razorDivBlock(p Property) string {
	var b strings.Builder
	b.WriteString("    <div class=\"mb-3\">\n")
	b.WriteString("        <label>" + p.DisplayName + "</label>\n")
	if strings.TrimSuffix(p.CSharpType, "?") == "Guid" {
		b.WriteString("        <InputText @bind-Value=\"form." + p.Name + "Text\" class=\"form-control\" />\n")
	} else {
		b.WriteString("        <" + p.UIControl + " @bind-Value=\"form." + p.Name + "\" class=\"form-control\" />\n")
	}
	b.WriteString("    </div>")
	return b.String()
}

func razorTdLine(p Property) string { return "            <td>@item." + p.Name + "</td>" }

func razorEditAssignLine(p Property) string {
	if strings.TrimSuffix(p.CSharpType, "?") == "Guid" {
		return "        form." + p.Name + "Text = item." + p.Name + ".ToString();"
	}
	return "        form." + p.Name + " = item." + p.Name + ";"
}

func razorRequestArgPiece(p Property) string {
	if strings.TrimSuffix(p.CSharpType, "?") == "Guid" {
		return "Guid.Parse(form." + p.Name + "Text)"
	}
	return "form." + p.Name
}

func razorEditorFieldLine(p Property) string {
	if strings.TrimSuffix(p.CSharpType, "?") == "Guid" {
		return "        public string " + p.Name + "Text { get; set; } = \"\";"
	}
	return "        public " + p.CSharpType + " " + p.Name + " { get; set; } = default!;"
}

func patchRenoirRazor(path string, existing EntityMeta, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	last := existing.Properties[len(existing.Properties)-1]

	divAnchor := razorDivBlock(last)
	var divBlocks []string
	for _, p := range newProps {
		divBlocks = append(divBlocks, razorDivBlock(p))
	}
	newContent, changed := insertAfterAnchor(content, divAnchor, "\n"+strings.Join(divBlocks, "\n"), 1)
	if !changed {
		return fmt.Errorf("razor %s: form field for %q not found", path, last.Name)
	}
	content = newContent

	tdAnchor := razorTdLine(last)
	var tdLines []string
	for _, p := range newProps {
		tdLines = append(tdLines, razorTdLine(p))
	}
	newContent, changed = insertAfterAnchor(content, tdAnchor, "\n"+strings.Join(tdLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("razor %s: table cell for %q not found", path, last.Name)
	}
	content = newContent

	editAnchor := razorEditAssignLine(last)
	var editLines []string
	for _, p := range newProps {
		editLines = append(editLines, razorEditAssignLine(p))
	}
	newContent, changed = insertAfterAnchor(content, editAnchor, "\n"+strings.Join(editLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("razor %s: EditAsync assignment for %q not found", path, last.Name)
	}
	content = newContent

	newContent, changed = replaceArgList(content, existing.Properties, newProps, razorRequestArgPiece, leadingSpaceJoin)
	if !changed {
		return fmt.Errorf("razor %s: Request constructor arg list not found", path)
	}
	content = newContent

	var editorLines []string
	for _, p := range newProps {
		editorLines = append(editorLines, razorEditorFieldLine(p))
	}
	newContent, changed = insertLinesInBlock(content, "private sealed class "+existing.Name+"Editor", editorLines)
	if !changed {
		return fmt.Errorf("razor %s: Editor class not found or already patched", path)
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchRenoirConfiguration(path, aggregate string, newProps []Property, dryRun bool) error {
	content, err := readPatchFile(path)
	if err != nil {
		return err
	}
	var lines []string
	for _, p := range newProps {
		if strings.TrimSuffix(p.CSharpType, "?") == "string" {
			lines = append(lines, "        builder.Property(x => x."+p.Name+").HasMaxLength(200);")
		}
	}
	if len(lines) == 0 {
		return nil
	}
	newContent, changed := insertLinesInBlock(content, "public void Configure(EntityTypeBuilder<"+aggregate+"> builder)", lines)
	if !changed {
		return fmt.Errorf("configuration %s: Configure method not found or maxlength already present", path)
	}
	return writePatchFile(path, newContent, dryRun)
}

func patchRenoirCrudService(path string, existing EntityMeta, newProps []Property, dryRun bool) error {
	patches := []argPatch{
		{prefixedPiece("x"), tokenJoin("x.Id")},
		{prefixedPiece("entity"), tokenJoin("entity.Id")},
		{prefixedPiece("request"), leadingSpaceJoin},
		{recordParamPiece, leadingSpaceJoin},
		{recordParamPiece, tokenJoin("long Id")},
	}
	return patchArgListsInFile(path, existing.Properties, newProps, patches, dryRun)
}

func patchRenoirAggregateField(r addRequest, m *Manifest, existing EntityMeta, newProps []Property) error {
	project := r.Project
	dir := filepath.Join(project, "src", m.Project+".DomainModel", existing.Context)
	aggPath := filepath.Join(dir, existing.Name+".cs")
	methodsPath := filepath.Join(dir, existing.Name+".Methods.cs")

	content, err := readPatchFile(aggPath)
	if err != nil {
		return err
	}
	newContent, changed := replaceArgList(content, existing.Properties, newProps, ctorParamPiece, leadingSpaceJoin)
	if !changed {
		return fmt.Errorf("aggregate %s: constructor parameter list not found", aggPath)
	}
	content = newContent

	last := existing.Properties[len(existing.Properties)-1]
	assignAnchor := domainAssignLine(last, true)
	var assignLines []string
	for _, p := range newProps {
		assignLines = append(assignLines, domainAssignLine(p, true))
	}
	newContent, changed = insertAfterAnchor(content, assignAnchor, "\n"+strings.Join(assignLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("aggregate %s: constructor assignment %q not found", aggPath, assignAnchor)
	}
	content = newContent

	var declLines []string
	for _, p := range newProps {
		declLines = append(declLines, autoPropLine(p, "private set"))
	}
	newContent, changed = insertBeforeMarker(content, "    // aspgen:navigation", strings.Join(declLines, "\n"))
	if !changed {
		return missingMarkerErr(aggPath, "// aspgen:navigation")
	}
	if err := writePatchFile(aggPath, newContent, r.DryRun); err != nil {
		return err
	}

	content, err = readPatchFile(methodsPath)
	if err != nil {
		return err
	}
	newContent, changed = replaceArgList(content, existing.Properties, newProps, ctorParamPiece, leadingSpaceJoin)
	if !changed {
		return fmt.Errorf("aggregate methods %s: Update parameter list not found", methodsPath)
	}
	content = newContent
	newContent, changed = insertAfterAnchor(content, assignAnchor, "\n"+strings.Join(assignLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("aggregate methods %s: Update assignment %q not found", methodsPath, assignAnchor)
	}
	content = newContent
	importAnchor := "        " + last.Name + " = other." + last.Name + ";"
	var importLines []string
	for _, p := range newProps {
		importLines = append(importLines, "        "+p.Name+" = other."+p.Name+";")
	}
	newContent, changed = insertAfterAnchor(content, importAnchor, "\n"+strings.Join(importLines, "\n"), 1)
	if !changed {
		return fmt.Errorf("aggregate methods %s: Import assignment %q not found", methodsPath, importAnchor)
	}
	if err := writePatchFile(methodsPath, newContent, r.DryRun); err != nil {
		return err
	}

	configPath := filepath.Join(project, "src", m.Project+".Persistence", existing.Name+"Configuration.cs")
	if err := patchRenoirConfiguration(configPath, existing.Name, newProps, r.DryRun); err != nil {
		return err
	}

	appDir := filepath.Join(project, "src", m.Project+".Application")
	crudPath := filepath.Join(appDir, existing.Name+"CrudService.cs")
	if _, err := os.Stat(crudPath); err == nil {
		if err := patchRenoirCrudService(crudPath, existing, newProps, r.DryRun); err != nil {
			return err
		}
		validatorPath := filepath.Join(appDir, existing.Name+"Validator.cs")
		if err := patchValidatorFile(validatorPath, "public "+existing.Name+"Validator()", newProps, true, r.DryRun); err != nil {
			return err
		}
	}

	razorPath := filepath.Join(project, "src", m.Project+".AppBlazor", "Components", "Pages", existing.Context, existing.Name+"Crud.razor")
	if _, err := os.Stat(razorPath); err == nil {
		if err := patchRenoirRazor(razorPath, existing, newProps, r.DryRun); err != nil {
			return err
		}
	}

	return nil
}
