package generator

// topLevelHelp is printed for `aspgen`, `aspgen --help`, `aspgen -h`, and `aspgen help`.
const topLevelHelp = `aspgen scaffolds ASP.NET Core Clean Architecture APIs and Prism/DryIoc WPF apps from templates.

Usage:
  aspgen new NAME [flags]        Create a new project (tree + solution + manifest)
  aspgen add KIND NAME [flags]   Add a component to an existing project
  aspgen import-db [flags]       Add entities to an existing project from a SQL DDL script
  aspgen templates list|export PATH|validate PATH
  aspgen version                 Print the aspgen version

Run "aspgen new --help", "aspgen add --help", or "aspgen import-db --help" for flag details.

Flags accept three equivalent forms: --flag value, --flag:value, -flag:value
`

// newHelp is printed for `aspgen new --help`.
const newHelp = `Usage:
  aspgen new NAME --context CTX --arch ar|dm|cqrs|es [flags]

Context/arch engine flags:
  --context CTX      Bounded context name; presence triggers this engine instead of --app/--backend
  --arch TIER        ar | dm | cqrs | es (all four tiers are implemented)
  -ui UI             wpf (Prism/DryIoc Desktop, full per-aggregate CRUD screens; HTTP for
                     cqrs/es, in-process CrudService calls for dm) | blazor (Blazor Server,
                     same CRUD screens over HTTP, cqrs/es only) | spa (CORS+OpenAPI+Scalar
                     on the WebApi host, no frontend project, cqrs/es only) | mvc (ASP.NET
                     Core MVC, in-process CrudService calls, dm only); omit for a headless
                     project
  --database DB      sqlite | postgres (default sqlite; dm-tier projects are class libraries
                     only, no host attaches the provider yet; cqrs/es-tier projects get their
                     own WebApi Minimal API host at src\WebApi)
  --output PATH      Output directory (default: project NAME)
  --templates PATH   Use a custom template directory instead of the embedded set
  --no-tests         Skip generating the {Project}.UnitTests / {Project}.IntegrationTests
                     projects (generated by default; dm-tier gets UnitTests only, no host to
                     hit over HTTP)
  --dry-run          Print what would be created without writing files
  --force            Overwrite existing files

Every context/arch project also generates scripts\ci.ps1 (restore, build, test, and
optionally -Publish the WebApi host; skipped automatically for headless dm-tier).

Examples:
  aspgen new Accounting --context Billing --arch ar --output ./Accounting
  aspgen new Accounting --context Billing --arch dm --output ./Accounting
  aspgen new Billing --context Sales --arch cqrs --output ./Billing
  aspgen new Billing --context Sales --arch es --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui spa --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui wpf --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui blazor --output ./Billing
  aspgen new Accounting --context Billing --arch dm -ui mvc --output ./Accounting
  aspgen new Accounting --context Billing --arch dm -ui wpf --output ./Accounting
`

// addHelp is printed for `aspgen add --help`.
const addHelp = `Usage:
  aspgen add KIND NAME [prop:type ...] [flags]

Kinds:
  entity NAME prop:type... --context CTX  ar-tier context entity
  entity-field NAME prop:type... Add properties to an existing entity/aggregate
  ui                            Attach a UI to a --context/--arch engine project
                                 [--framework wpf|blazor|spa|mvc] (blazor/spa are cqrs/es
                                 only over HTTP; wpf works on cqrs/es over HTTP or dm
                                 in-process; mvc is dm-only in-process); each renders full
                                 per-aggregate CRUD screens for every aggregate already in
                                 the project, and future "add aggregate" calls keep adding
                                 screens automatically once a UI is attached
  context NAME --arch TIER      Bounded context (ar|dm|cqrs|es engine context)
  aggregate NAME prop:type... --context CTX [--no-crud]  (dm+ engine context; cqrs-tier
                                 also generates Command/Query/Handler vertical-slice files
                                 and mounts Minimal API endpoints on the WebApi host;
                                 es-tier aggregates are event-sourced (EventSourcedAggregate
                                 + event replay) and get the same vertical-slice/endpoint
                                 treatment backed by a generated
                                 {Aggregate}EventStoreRepository + read-model projection)
  value-object NAME prop:type... --context CTX  (dm+ engine context)
  domain-service NAME --context CTX  (dm+ engine context)
  repository NAME --aggregate AGG --context CTX  (dm+ engine context; cqrs-tier also
                                 registers the repository with the WebApi host's DI
                                 container; not applicable to es-tier aggregates, which
                                 already have a generated EventStoreRepository)
  event NAME prop:type... --context CTX  (dm+ engine context)

Common flags:
  --project PATH     Path to the generated project (default: search this dir and parents for .aspgen/manifest.json)
  --theme wpfui      WPF-UI Fluent theme (ui)
  --theme-mode MODE  light | dark (default light; requires --theme wpfui)
  --dry-run          Print what would change without writing files
  --force            Overwrite existing files

Examples:
  aspgen add entity Product name:string price:decimal --context Catalog --project ./Accounting
  aspgen add entity-field Product notes:string --project ./Accounting
  aspgen add context Sales --arch cqrs --project ./Billing
  aspgen add ui spa --framework spa --project ./Billing
  aspgen add aggregate Order number:string total:decimal --context Sales --project ./Billing
`

// importDBHelp is printed for `aspgen import-db --help`.
const importDBHelp = `Usage:
  aspgen import-db --project PATH --script PATH --provider PROVIDER --context CTX [flags]

Adds an entity per selected table to an existing ar-tier context, the same
way "add entity" would, then writes a schema.sql backup snapshot at the
project root. Does not run "dotnet ef migrations" — that remains a manual
step against the generated entities/DbContext.

Flags:
  --project PATH     Path to the generated project (default: search this dir and parents for .aspgen/manifest.json)
  --script PATH      SQL DDL script to parse
  --provider P       sqlite | postgres | sqlserver | mysql (required)
  --tables T         all (default) or a comma list of table names to import
  --context CTX      Bounded context every imported table becomes an entity in (required)
  --dry-run          Print what would change without writing files
  --force            Overwrite existing files

Example:
  aspgen import-db --project ./Accounting --script schema.sql --provider postgres --context Catalog --tables all
`
