package generator

// topLevelHelp is printed for `aspgen`, `aspgen --help`, `aspgen -h`, and `aspgen help`.
const topLevelHelp = `aspgen scaffolds ASP.NET Core Clean Architecture APIs and Prism/DryIoc WPF apps from templates.

Usage:
  aspgen new NAME [flags]        Create a new project (tree + solution + manifest)
  aspgen add KIND NAME [flags]   Add a component to an existing project
  aspgen import-db [flags]       Add entities to an existing project from a SQL DDL script
  aspgen templates list|export PATH|validate PATH
  aspgen version                 Print the aspgen version

Run "aspgen new --help", "aspgen add --help", or "aspgen import-db --help" for flag details.

Flags accept three equivalent forms: --flag value, --flag:value, -flag:value
`

// newHelp is printed for `aspgen new --help`.
const newHelp = `Usage:
  aspgen new NAME --context CTX --arch ar|dm|cqrs|es [flags]
  aspgen new NAME --app webapi|wpf|blazor|fullstack [flags]   (legacy, deprecated, see below)

Context/arch engine flags:
  --context CTX      Bounded context name; presence triggers this engine instead of --app/--backend
  --arch TIER        ar | dm | cqrs | es (all four tiers are implemented)
  -ui UI             wpf (Prism/DryIoc Desktop, full per-aggregate CRUD screens; HTTP for
                     cqrs/es, in-process CrudService calls for dm) | blazor (Blazor Server,
                     same CRUD screens over HTTP, cqrs/es only) | spa (CORS+OpenAPI+Scalar
                     on the WebApi host, no frontend project, cqrs/es only) | mvc (ASP.NET
                     Core MVC, in-process CrudService calls, dm only); omit for a headless
                     project
  --database DB      sqlite | postgres (default sqlite; dm-tier projects are class libraries
                     only, no host attaches the provider yet; cqrs/es-tier projects get their
                     own WebApi Minimal API host at src\WebApi)
  --output PATH      Output directory (default: project NAME)
  --templates PATH   Use a custom template directory instead of the embedded set
  --no-tests         Skip generating the {Project}.UnitTests / {Project}.IntegrationTests
                     projects (generated by default; dm-tier gets UnitTests only, no host to
                     hit over HTTP)
  --dry-run          Print what would be created without writing files
  --force            Overwrite existing files

Every context/arch project also generates scripts\ci.ps1 (restore, build, test, and
optionally -Publish the WebApi host; skipped automatically for headless dm-tier).

Examples:
  aspgen new Accounting --context Billing --arch ar --output ./Accounting
  aspgen new Accounting --context Billing --arch dm --output ./Accounting
  aspgen new Billing --context Sales --arch cqrs --output ./Billing
  aspgen new Billing --context Sales --arch es --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui spa --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui wpf --output ./Billing
  aspgen new Billing --context Sales --arch cqrs -ui blazor --output ./Billing
  aspgen new Accounting --context Billing --arch dm -ui mvc --output ./Accounting
  aspgen new Accounting --context Billing --arch dm -ui wpf --output ./Accounting

Legacy flags (deprecated, kept working, no longer advertised as the default path):
  --app TARGET       webapi | wpf | blazor | fullstack (default webapi)
  --simple           Single-project Active Record CRUD (webapi/fullstack; not with --backend)
  --backend ddd      Clean Architecture DDD/CQRS layers (webapi/fullstack, or wpf for local-only DDD)
  --database DB      sqlite | postgres (default sqlite; webapi/fullstack/wpf+ddd only)
  --theme wpfui      WPF-UI Fluent theme (wpf/fullstack only)
  --theme-mode MODE  light | dark (default light; requires --theme wpfui)
  --seed dummy [N]   N sample records per entity, default 3 (needs --simple or --backend ddd)
  --script PATH      SQL DDL script to import entities from (needs --provider)
  --provider P       sqlite | postgres | sqlserver | mysql (required with --script)
  --tables T         all (default) or a comma list of table names to import
  --context CTX      Bounded context imported tables become aggregates in (blazor only, required with --script there)

Legacy examples:
  aspgen new MyApp --app fullstack --simple --output ./MyApp
  aspgen new MyApp --app webapi --backend ddd --database postgres
  aspgen new MyApp --app webapi --simple --script schema.sql --provider postgres --tables all
  aspgen new RenoirDemo --app blazor
  aspgen new RenoirDemo --app blazor --script schema.sql --provider sqlserver --context Catalog
`

// addHelp is printed for `aspgen add --help`.
const addHelp = `Usage:
  aspgen add KIND NAME [prop:type ...] [flags]

Kinds:
  entity NAME prop:type...      Simple-profile entity (Domain + API + seed), or an
                                 ar-tier context entity with --context CTX
  entity-field NAME prop:type... Add properties to an existing entity/aggregate
  module NAME                   WPF Prism module (run "add ui" first)
  database NAME                 Register/switch the persistence provider
  service NAME                  Application service (non-simple webapi/fullstack)
  feature NAME prop:type...     Web API vertical-slice CRUD feature
  ui                            Add the WPF/Prism UI to a webapi project [--framework wpf],
                                 or attach a UI to a --context/--arch engine project
                                 [--framework wpf|blazor|spa|mvc] (blazor/spa are cqrs/es
                                 only over HTTP; wpf works on cqrs/es over HTTP or dm
                                 in-process; mvc is dm-only in-process); each renders full
                                 per-aggregate CRUD screens for every aggregate already in
                                 the project, and future "add aggregate" calls keep adding
                                 screens automatically once a UI is attached
  context NAME [--arch TIER]    Bounded context (blazor/Renoir profile, or ar|dm|cqrs|es
                                 engine context with --arch; all four tiers are implemented)
  aggregate NAME prop:type... --context CTX [--no-crud]  (blazor/Renoir profile, or a
                                 dm+ engine context; cqrs-tier also generates
                                 Command/Query/Handler vertical-slice files and mounts
                                 Minimal API endpoints on the WebApi host; es-tier aggregates
                                 are event-sourced (EventSourcedAggregate + event replay) and
                                 get the same vertical-slice/endpoint treatment backed by a
                                 generated {Aggregate}EventStoreRepository + read-model projection)
  value-object NAME prop:type... --context CTX  (blazor/Renoir profile, or a dm+ engine context)
  domain-service NAME --context CTX  (blazor/Renoir profile, or a dm+ engine context)
  repository NAME --aggregate AGG --context CTX  (blazor/Renoir profile, or a dm+ engine
                                 context; cqrs-tier also registers the repository with the
                                 WebApi host's DI container; not applicable to es-tier
                                 aggregates, which already have a generated EventStoreRepository)
  event NAME prop:type... --context CTX  (blazor/Renoir profile, or a dm+ engine context)

Common flags:
  --project PATH     Path to the generated project (default: search this dir and parents for .aspgen/manifest.json)
  --theme wpfui      WPF-UI Fluent theme (ui/module)
  --theme-mode MODE  light | dark (default light; requires --theme wpfui)
  --dry-run          Print what would change without writing files
  --force            Overwrite existing files

Examples:
  aspgen add entity Customer name:string age:int active:bool --project ./MyApp
  aspgen add entity-field Customer notes:string --project ./MyApp
  aspgen add context Catalog --project ./RenoirDemo
  aspgen add ui spa --framework spa --project ./Billing
  aspgen add aggregate Product name:string price:decimal --context Catalog --project ./RenoirDemo
`

// importDBHelp is printed for `aspgen import-db --help`.
const importDBHelp = `Usage:
  aspgen import-db --project PATH --script PATH --provider PROVIDER [flags]

Adds an entity per selected table to an existing project, the same way
"add entity" would (simple/ddd backend, webapi/fullstack/wpf profiles), or
an aggregate per selected table the same way "add aggregate" would on the
blazor/Renoir profile (requires --context), then writes a schema.sql backup
snapshot at the project root. Does not run "dotnet ef migrations" — that
remains a manual step against the generated entities/DbContext.

Flags:
  --project PATH     Path to the generated project (default: search this dir and parents for .aspgen/manifest.json)
  --script PATH      SQL DDL script to parse
  --provider P       sqlite | postgres | sqlserver | mysql (required)
  --tables T         all (default) or a comma list of table names to import
  --backend ddd      Override the project's backend profile (default: the project's own backend)
  --context CTX      Bounded context every imported table becomes an aggregate in (blazor/Renoir profile only, required there)
  --dry-run          Print what would change without writing files
  --force            Overwrite existing files

Examples:
  aspgen import-db --project ./MyApp --script schema.sql --provider postgres --tables all
  aspgen import-db --project ./RenoirDemo --script schema.sql --provider sqlserver --context Catalog
`
